export { default as banner01 } from "./banner-01.jpg"
export { default as banner02 } from "./banner-02.jpg"
export { default as banner03 } from "./banner-03.jpg"
export { default as banner04 } from "./banner-04.jpg"
export { default as banner05 } from "./banner-05.jpg"
export { default as banner06 } from "./banner-06.jpg"
export { default as banner07 } from "./banner-07.jpg"
export { default as banner08 } from "./banner-08.jpg"
export { default as banner09 } from "./banner-09.jpg"
export { default as banner10 } from "./banner-10.jpg"
export { default as banner11 } from "./banner-11.jpg"
export { default as banner12 } from "./banner-12.jpg"
export { default as banner13 } from "./banner-13.jpg"
export { default as banner14 } from "./banner-14.jpg"

export { default as bgBanner01 } from "./bg-banner-01.jpg"
export { default as bgBanner02 } from "./bg-banner-02.jpg"

export { default as bgVideo01 } from "./bg-video-01.jpg"

export { default as blog01 } from "./blog-01.jpg"
export { default as blog02 } from "./blog-02.jpg"
export { default as blog03 } from "./blog-03.jpg"
export { default as blog04 } from "./blog-04.jpg"
export { default as blog05 } from "./blog-05.jpg"
export { default as blog06 } from "./blog-06.jpg"
export { default as blog07 } from "./blog-07.jpg"
export { default as blog08 } from "./blog-08.jpg"
export { default as blog09 } from "./blog-09.jpg"
export { default as blog10 } from "./blog-10.jpg"

export { default as gallery01 } from "./gallery-01.jpg"
export { default as gallery02 } from "./gallery-02.jpg"
export { default as gallery03 } from "./gallery-03.jpg"
export { default as gallery04 } from "./gallery-04.jpg"
export { default as gallery05 } from "./gallery-05.jpg"
export { default as gallery06 } from "./gallery-06.jpg"
export { default as gallery07 } from "./gallery-07.jpg"
export { default as gallery08 } from "./gallery-08.jpg"
export { default as gallery09 } from "./gallery-09.jpg"
export { default as gallery10 } from "./gallery-10.jpg"
export { default as gallery11 } from "./gallery-11.jpg"
export { default as gallery12 } from "./gallery-12.jpg"
export { default as gallery13 } from "./gallery-13.jpg"
export { default as gallery14 } from "./gallery-14.jpg"
export { default as gallery15 } from "./gallery-15.jpg"

export { default as headingPages01 } from "./heading-pages-01.jpg"
export { default as headingPages02 } from "./heading-pages-02.jpg"
export { default as headingPages03 } from "./heading-pages-03.jpg"
export { default as headingPages04 } from "./heading-pages-04.jpg"
export { default as headingPages05 } from "./heading-pages-05.jpg"
export { default as headingPages06 } from "./heading-pages-06.jpg"

export { default as item01 } from "./item-01.jpg"
export { default as item02 } from "./item-02.jpg"
export { default as item03 } from "./item-03.jpg"
export { default as item04 } from "./item-04.jpg"
export { default as item05 } from "./item-05.jpg"
export { default as item06 } from "./item-06.jpg"
export { default as item07 } from "./item-07.jpg"
export { default as item08 } from "./item-08.jpg"
export { default as item09 } from "./item-09.jpg"
export { default as item10 } from "./item-10.jpg"
export { default as item11 } from "./item-11.jpg"
export { default as item12 } from "./item-12.jpg"
export { default as item13 } from "./item-13.jpg"
export { default as item14 } from "./item-14.jpg"
export { default as item15 } from "./item-15.jpg"
export { default as item16 } from "./item-16.jpg"
export { default as item17 } from "./item-17.jpg"

export { default as itemCart01 } from "./item-cart-01.jpg"
export { default as itemCart02 } from "./item-cart-02.jpg"
export { default as itemCart03 } from "./item-cart-03.jpg"
export { default as itemCart04 } from "./item-cart-04.jpg"
export { default as itemCart05 } from "./item-cart-05.jpg"
export { default as itemCart06 } from "./item-cart-06.jpg"

export { default as masterSlide01 } from "./master-slide-01.jpg"
export { default as masterSlide02 } from "./master-slide-02.jpg"
export { default as masterSlide03 } from "./master-slide-03.jpg"
export { default as masterSlide04 } from "./master-slide-04.jpg"
export { default as masterSlide05 } from "./master-slide-05.jpg"
export { default as masterSlide06 } from "./master-slide-06.jpg"
export { default as masterSlide07 } from "./master-slide-07.jpg"
export { default as masterSlide08 } from "./master-slide-08.jpg"

export { default as productDetail01 } from "./product-detail-01.jpg"
export { default as productDetail02 } from "./product-detail-02.jpg"
export { default as productDetail03 } from "./product-detail-03.jpg"

export { default as shopItem09 } from "./shop-item-09.jpg"

export { default as thumbItem01 } from "./thumb-item-01.jpg"
export { default as thumbItem02 } from "./thumb-item-02.jpg"
export { default as thumbItem03 } from "./thumb-item-03.jpg"

export { default as untitled } from "./Untitled-5.jpg"